- name: "Instalación de JDK, Tomcat y MySQL"
  hosts: webservers
  become: yes
  gather_facts: yes

  vars_files:
    - ../group_vars/webservers.yml

  tasks:
    - import_tasks: install-jdk.yml
    - import_tasks: install-tomcat.yml
    - import_tasks: install-mysql.yml
